directories:
  output: dist
  buildResources: build
appId: com.pgdelcampo.panel
productName: PG del Campo - Panel
publish:
  - provider: github
    owner: proglodelcam
    repo: proglodelcam-commits
    releaseType: release
win:
  target:
    - nsis
  icon: build/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: PG del Campo Panel
mac:
  category: public.app-category.business
  target:
    - dmg
  icon: build/icon.icns
linux:
  target:
    - AppImage
    - deb
  category: Office
  icon: build/icon.png
files: []
electronVersion: 31.0.0
